name: Trigger on Review Comment

on:
  issue_comment:
    types: [created]

jobs:
  check_review_comment:
    runs-on: ubuntu-latest
    steps:
    - name: Run action if review comment
      if: ${{ github.event.issue.pull_request }}
      run: |
        echo "This is a review comment, you can trigger your action here."
    - name: Run InferPRResponse
      if: steps.check_comment.outputs.is_review_comment == 'true'
      uses: thatnerd2/InferPRResponseAction@main
      with:
        comment_id: ${{ github.event.comment.id }}
      env:
        CPD_GITHUB_TOKEN: ${{ secrets.INFERPRACTION_GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
        OPENAI_DEPLOYMENT_NAME: ${{ secrets.OPENAI_DEPLOYMENT_NAME }}


