name: Run InferSharp PR Response
on: [issue_comment]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # check if comment is on a PR
      - name: Check if PR
        id: check_if_pr
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.INFERPRACTION_GITHUB_TOKEN }}
          script: |
            const issue = context.issue;
            const isPr = issue.hasOwnProperty('pull_request');
            console.log(isPr);
            return isPr;
      - name: Run InferPRResponse
        uses: thatnerd2/InferPRResponseAction@main
        with:
          comment_id: ${{ github.event.comment.id }}
        env:
          CPD_GITHUB_TOKEN: ${{ secrets.INFERPRACTION_GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_DEPLOYMENT_NAME: ${{ secrets.OPENAI_DEPLOYMENT_NAME }}


